### ISSUE TITLE
Explore applying `dask` to `nwis_client` requests

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#146]
@aaraney 

Encountered a use-case where `nwis_client.iv.get` was attempting to generate a `pandas.DataFrame` larger than memory. This involved retrieving ~1 year of data from ~1000 sites. Since it's `pandas` this of course failed. We were able to work around the issue by chunking the request into batches of ~100 sites, but this seems like something the `nwis_client` could do on its own.

I'm wondering if we can come up with a scalable chunking and caching strategy similar to that used by `nwm_client_new` and introduce an interface that returns a `dask` dataframe for processing larger than memory data sets. Something like: `hydrotools.nwis_client.iv.get_dask_dataframe`.

**Comment by aaraney** [comment]
Thanks for doing a little digging, @jarq6c. Having skimmed the Parquet specification, I see why it is the preferred solution and why we might want to prefer it for this application as well. From my reading, parquet is opinionated about compression and less so about chunking and splitting a dataset into multiple files. Where as with zarr, it is much more of a framework when it comes to compression (its easy to changes algorithms), however _is_ opinionated about chunking. [Specifically](https://zarr.readthedocs.io/en/stable/spec/v2.html#metadata), 

> Chunks: A list of integers defining the length of each dimension of a chunk of the array. Note that all chunks within a Zarr array have the same shape.

So, in the context of this problem, where we are not certain about data continuity, parquet seems the better choice. 

As for how to proceed with this feature, I think sticking with the `nwis_client` and also possibly contributing to `cache` is the best way forward. We have yet to take advantage of alpha/beta/pre-release/development versions on pypi and I think this could be a good introduction to that kind of development flow. I wish there were a nightly tag instead of alpha/beta etc. as that is how I am conceptualizing the flow. For example, additions to `nwis_client` could be released using a develop or pre-release tag (see [pep 440](https://www.python.org/dev/peps/pep-0440/#developmental-releases)). This would allow for users who want to take on the risk of using new features to do so, as well as, inform users that do not want to take the risk that new additions are being made. As always though, I am always open to hearing a different prospective and would like to get your opinion!

**Comment by jarq6c** [comment]
Closing old issues.
