### ISSUE TITLE
NWIS IV Client `FutureWarning`

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#209]
When using the nwis iv client, I receive this warning:

```console
~/env/lib/python3.8/site-packages/hydrotools/nwis_client/iv.py:283: FutureWarning: In a future version, 
`df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To 
retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, 
`df.isetitem(i, newvals)` dfs.loc[:, "value"] = pd.to_numeric(dfs["value"], downcast="float")
```

**Comment by aaraney** [comment]
Thanks for opening and documenting this, @jarq6c. I should have some bandwidth late into the afternoon to look into this and also checkout the PR's that i've neglected for longer that I would like to admit.

**Comment by aaraney** [comment]
This looks like a pretty easy fix. We should just swap `df.loc` for setting with `df[]`. We need to set by replacement (copy) rather than in-place because are changing the data type of the underlying array when we downcast. 

I'm glad to see that pandas is improving the consistency of it's copy vs view semantics.

**Comment by aaraney** [comment]
For record sake, the `FutureWarning` was adding in `1.5.0`. You can find more details about it [here](https://pandas.pydata.org/docs/whatsnew/v1.5.0.html#inplace-operation-when-setting-values-with-loc-and-iloc).
