### ISSUE TITLE
nwis_client: Retrieving large amounts of data takes too long

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#50]
Case study: A user needs to conduct a long evaluation and wants 25 years of streamflow data from 2000+ USGS gage locations.

Obstacles:

1. We currently only parallelize by site, can we parallelize by chunking in time?
2. How do we get around limited memory?
3. Will this break `requests_cache`?
4. Can a `DataFrame` cache help us here?

Based on a use-case from @hellkite500 

@aaraney not necessarily looking for solutions here yet. Just wanted to start the discussion. The `nwis_client` tool was really the first tool we fleshed out. So, it seems fitting to start discussions about scaling `evaluation_tools` here.

**Comment by aaraney** [comment]
I have conflicting views about this. On one hand, I totally get the desire to have the Swiss army knife of data retrieval tools, but on the other hand I think expecting that one software can fulfill every use case without having to write a bit of code yourself is just not realistic. 

> @aaraney not necessarily looking for solutions here yet.

Well below are some unsolicited starting solutions.

> Obstacles:
> 
> We currently only parallelize by site, can we parallelize by chunking in time?

I think we can achieve this by using a defined time period. So for example, time periods greater than 1 year are chunked by year. I don't see this being an option that the user can specify like the `partition_max_size` we have now that determines when to split by site. I make this point because dealing with time just gets messy thanks in part to the Romans. Chunking by month also seems too granular, but I'm happy to hear what others think about this and other proposed approaches.

> How do we get around limited memory?

This is a more difficult question to answer. I guess first off, to answer this you've got to come up with a system agnostic heuristic that answers, "should I save too disk or not?" Additionally, when does the software ask this question and how often? Or is it just a one time thing (at run time)? I just think there are a lot of edge cases that require speaking to if we want to fully satisfy this question.

As for how can we actually get around the memory barrier, I think a simple sqlite db should suffice. As workers complete a job instead of leaving their response in memory, they write to a local sqlite db that can be queried. The sqlite db could reflect the `evaluation_tools` canonical dataframe. I think there is a valid argument for using `HDF` here or something like `feather` and im open to hear those arguments, just trying to stay true to the `evaluation_tools` mission of tools for data scientists. SQL syntax, while not as common in hydrology in my experience, is a tool most data scientists have.

> Will this break requests_cache?

If you mean once you make the call that hits `NWIS` if you make the same identical call will it hit `NWIS` again? That should still work properly.

> Can a DataFrame cache help us here?

Probably or some form of a DataFrame cache. I kind of alluded to a solution for the DataFrame cache above that would suffice in solving this problem.

**Comment by aaraney** [comment]
Just an update to this issue after some outside conversation. I was not on the same page about the intended strengths of the `nwis_client` over say something like `dataRetrieval`. I was under the impression that the main benefits of our `nwis_client` were the canonical dataframe, naive utc time handling, and some performance increases brought by splitting up data retrieval by station. I was not under the impression that the `nwis_client`'s purpose is to optimize data retrieval over both time and space at potentially the HPC level. With that context now in mind, I redact most of my prior comment and will start looking into options for a different cache mechanism and time partitioning heuristic.

**Comment by jarq6c** [comment]
@aaraney Oh you were right! I think those are _currently_ the main benefits along with the ability to retrieve large volumes of data efficiently using `multiprocessing`. This ticket is really about scalability. How much can we push NWIS and can we implement methods that make it easier to run (and rerun) data hungry workflows?

**Comment by jarq6c** [comment]
Note: I was recently implemented a workflow that need 18 hours of NWIS data from 7,541 sites. `nwis_client` retrieved the data in ~50 seconds which is comparable to our internal services.  I'm not sure we can do much better than this. Deserializing the json and optimizing the dataframes is still a CPU bound task, so `multiprocessing` may continue to be an optimal enough solution. Where we could improve is how the data is cached. Based on various conversations, I think USGS expects you to pull the data once and only request new or modified data thereafter.
